apiVersion: v1
kind: Service
metadata:
  name: finance
  namespace: adventurer
  labels:
    app: finance
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: finance

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance
  namespace: adventurer
  labels:
    app: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: finance
    spec:
      restartPolicy: Always
      containers:
        - name: finance
          image: localhost:32000/adventurer/finance:latest
          env:
            - name: PORT
              value: "80"
            - name: BASE
              value: /v0
            - name: POSTGRES_HOST
              value: postgres.dev
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "10m"
              memory: "32Mi" 