apiVersion: v1
kind: Service
metadata:
  name: kanban
  namespace: adventurer
  labels:
    app: kanban
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: kanban

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban
  namespace: adventurer
  labels:
    app: kanban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: kanban
    spec:
      restartPolicy: Always
      containers:
        - name: kanban
          image: localhost:32000/adventurer/kanban:latest
          env:
            - name: PORT
              value: "80"
            - name: BASE
              value: /v0
            - name: MONGODB_CONNECTION
              value: mongodb://mongo.dev/kanban-development
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "10m"
              memory: "32Mi" 