---
apiVersion: v1
kind: Service
metadata:
  name: tower
  namespace: adventurer
  labels:
    app: tower
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: tower

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tower
  namespace: adventurer
  labels:
    app: tower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tower
    spec:
      restartPolicy: Always
      containers:
        - name: tower
          image: localhost:32000/adventurer/tower:latest
          imagePullPolicy: Always
          env:
            - name: LOGIN_URL
              value: https://adventurer.account-uat.stargate.36node.com/login?appId=60521fd8d7fcb30011764998
            - name: AUTH_ENDPOINT
              value: https://api.stargate.36node.com/auth/uat
            - name: KANBAN_ENDPOINT
              value: https://kanban.dev.stacktop.cn
            - name: NODE_ENV
              value: development
            - name: NAMESPACE
              value: adventurer
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "10m"
              memory: "32Mi"
